### ISSUE TITLE
Hello Sir, You haven`t added any burn functionality in the code . It is just the event you are passing . Please update the code ASAP

### ISSUE THREAD

**Issue by sky-vibhu** [ilionic/substrate-nfts#1]
**Motivation**

_Describe the need or frustration that motivated you to make this suggestion. Please note that the
goal of this project is to provide a general-purpose template project, so please take care when
suggesting features that may be specific to a particular use case._

**Suggested Solution**

_Describe your suggested solution to the need or frustration that you are experiencing._

**Alternatives**

_Describe any alternative solutions or features you considered and why you believe your suggested
solution is preferable._

**Additional Information**

_Provide any additional information that you believe may help us evaluate your suggestion._

**Comment by upendra-eth** [comment]
yes, I also wanna know, when will you update Todo functions

**Comment by ilionic** [comment]
Development moved here https://github.com/rmrk-team/rmrk-substrate
